### ISSUE TITLE
Competition Artwork Gallery

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/voxel-challenge#1]
Update on 22nd, April：

Thank you for your participation! The submission is closed. 

--------------------------------------------------------------
Please submit your Artwork by commenting below. Here is an example:

+ Artwork Name:
+ Your Repo Link:
+ Artwork Screenshot:

You can also write down the story behind your Artwork~

**Comment by rexwangcc** [comment]
Name: A Trainer's Collection
Link: https://github.com/rexwangcc/taichi-voxel-challenge
Screenshot (to be updated once I'm able to dump images from the render directly):
![1](https://user-images.githubusercontent.com/14366016/163705805-5d8829d9-1913-42a4-ad77-5b5f38fa54f7.png)
![2](https://user-images.githubusercontent.com/14366016/163705812-75492123-7a8c-4f66-afa7-eb3577c7b268.png)
![3](https://user-images.githubusercontent.com/14366016/163705814-10276115-df44-4c68-adeb-fd45ade0422b.png)

**Comment by maajor** [comment]
Name: The Girl with a Voxel Earring
Link: https://github.com/maajor/maajor-voxel-challenge
Screenshot:
![girl_with_pearl_ring](https://user-images.githubusercontent.com/4011861/163707688-fc464182-f608-4772-b4ae-048047edba26.jpg)

**Comment by houkensjtu** [comment]
Artwork Name: Voxel Taichi
Your Repo Link: https://github.com/houkensjtu/qbao_voxel_art
Artwork Screenshot:

**Comment by JinkunSun** [comment]
Name: Voxel-Galaxy
Link: https://github.com/JinkunSun/voxel-challenge-galaxy
Screenshot:
![galaxy](https://user-images.githubusercontent.com/97423107/163719601-f2ee2af2-596c-482a-948b-530ed687e9af.jpg)

**Comment by neozhaoliang** [comment]
Name: Voxel-My-Desktop
Link: https://github.com/neozhaoliang/voxel-challenge
Screenshot: 
![sceenshot2022-04-17-235406](https://user-images.githubusercontent.com/23307174/163722347-e76d80c6-9d4d-45bf-b26f-6fbc6075d91e.jpg)

**Comment by ailzhang** [comment]
Name: Pyramid 
Link: https://github.com/ailzhang/voxel-challenge
Screenshot:

![pyramid](https://user-images.githubusercontent.com/5248122/163745748-d3cde579-5918-4acf-8537-a2a2f4baec8b.jpg)

**Comment by victoriacity** [comment]
Name: City In 99 Lines
Link: https://github.com/victoriacity/voxel-challenge
Screenshot: 
![sceenshot2022-04-17-223227](https://user-images.githubusercontent.com/14038064/163751626-7ca171f7-bda9-4d27-8cc6-fa34b503fd3c.jpg)
![sceenshot2022-04-17-223303](https://user-images.githubusercontent.com/14038064/163751627-68a9fa01-601b-40a3-bb75-821f3e3c7df5.jpg)
![sceenshot2022-04-17-223357](https://user-images.githubusercontent.com/14038064/163751629-76b9338c-c954-429c-8d94-262727912b2c.jpg)
![sceenshot2022-04-17-223520](https://user-images.githubusercontent.com/14038064/163751630-954b7ea1-bd69-4039-a759-e287c24277b7.jpg)
![sceenshot2022-04-17-223543](https://user-images.githubusercontent.com/14038064/163751631-a16ef0d0-e0cd-4a17-a47b-a02737faa42f.jpg)
![sceenshot2022-04-17-223602](https://user-images.githubusercontent.com/14038064/163751618-7f73f54e-a6b1-484a-82b1-3c13e6761962.jpg)
![sceenshot2022-04-17-223627](https://user-images.githubusercontent.com/14038064/163751619-9827c230-76c0-4ed5-868e-ea9274fa83b0.jpg)
![sceenshot2022-04-17-223738](https://user-images.githubusercontent.com/14038064/163751620-92255057-f4bb-4038-8f61-052754b686a4.jpg)
![sceenshot2022-04-17-223805](https://user-images.githubusercontent.com/14038064/163751621-5081e831-5864-482c-ad23-318c647bd181.jpg)
![sceenshot2022-04-17-223846](https://user-images.githubusercontent.com/14038064/163751622-8ae62272-2a6f-4246-a5ed-75ae76b3cd93.jpg)
![sceenshot2022-04-17-223916](https://user-images.githubusercontent.com/14038064/163751623-d278a576-e5a5-42d7-adf4-d78e249968bb.jpg)

**Comment by chuandongyan** [comment]
Name: luan+mageicsquare
Link: https://github.com/chuandongyan/voxel-challenge
Screenshot:
![mageicsquare](https://user-images.githubusercontent.com/90600320/163794699-a2ebcbb4-b331-4520-8734-9707e102c517.jpg)
![luanqibazao](https://user-images.githubusercontent.com/90600320/163794720-d7184d9b-2717-41c4-bdf1-ad1e3aff003a.jpg)

**Comment by ltt1598** [comment]
Name: Voxel-Taichi-Lang(浪)
Link: [ltt1598/voxel-challenge](https://github.com/ltt1598/voxel-challenge)
Screenshot:
![sceenshot2022-04-17-202101](https://user-images.githubusercontent.com/2309174/163804504-b702962d-c778-453e-9cff-c0bf0e1432a0.jpg)

**Comment by yaolibin2011** [comment]
Name: Cartesian coordinate system?
Link: https://github.com/yaolibin2011/voxelchallenge-libin/commit/52393da5435b633929392eb93ebf68a793b95918
Behind the scene: Thanks @turbo0628 for helping me run examples on my Mac, and a huge thanks goes to @houkensjtu  for the Taichi 101 training. Last but not least, I used for loop for the first time. T.T
Screenshot:

<img width="1191" alt="截屏2022-04-18 19 43 20" src="https://user-images.githubusercontent.com/90166857/163805429-9f59c9f1-ca19-4717-bc3f-406a4389d476.png">

**Comment by lucywsq** [comment]
Name: A purple building
Link: https://github.com/lucywsq/siqi001
Credit to @houkensjtu for the Taichi 101 training! 👍 
![main2](https://user-images.githubusercontent.com/38712162/163806242-5ccc2265-5d92-42b4-b54a-89ea4cfd38e6.jpg)

**Comment by m1911star** [comment]
Name: voxel-gameboy
Link: https://github.com/m1911star/voxel-challenge
ScreenShot:
![gameboy](https://user-images.githubusercontent.com/4948120/163806530-d2d881f3-c0c0-4fb4-a649-217b14eba746.jpg)

**Comment by BillXu2000** [comment]
Name: raiden
Link: https://github.com/BillXu2000/taichi-voxel-challenge
ScreenShot:
![screenshot2022-04-18-234658](https://user-images.githubusercontent.com/22523147/163834841-8f464b7b-0c0b-4d8e-9248-16a594be8b8a.jpg)

**Comment by beiyuouo** [comment]
- Name: Voxel-Pac-Man
- Link: [https://github.com/beiyuouo/voxel-pac-man](https://github.com/beiyuouo/voxel-pac-man)
- Screenshot:
![demo1](https://user-images.githubusercontent.com/44976445/163842495-00fc6efd-60ad-42ca-8edb-e73093b7aeb0.jpg)
![demo2](https://user-images.githubusercontent.com/44976445/163842503-f741b42e-eeb9-490c-9900-9f1c8894315c.jpg)

Inspired by 《Pixels》~

**Comment by waitinautumn12** [comment]
Name: champion
Link: https://github.com/waitinautumn12/voxel-challenge
Screenshot:
<img width="1409" alt="WechatIMG113" src="https://user-images.githubusercontent.com/19163795/163990427-635ca021-922c-467b-9f71-db4fc1289063.png">

**Comment by yihong0618** [comment]
Name: skyline
Link: https://github.com/yihong0618/voxel-challenge
Screenshot:

<img width="958" alt="截屏2022-04-19 19 32 45" src="https://user-images.githubusercontent.com/15976103/163995014-338ca4e0-8f2f-4849-ad51-1e687a912916.png">

--- 
https://skyline.github.com

**Comment by raybobo** [comment]
# 21
-------
Name: cloud city
Link: https://github.com/raybobo/taichi-voxel-challenge
Screenshot:
![view1](https://user-images.githubusercontent.com/15867575/164228644-56c21cc2-4899-43f0-91b5-653d42eab109.jpg)
![view2](https://user-images.githubusercontent.com/15867575/164228665-53182b68-49a9-4f17-8f34-90e3346583bf.jpg)
![view3](https://user-images.githubusercontent.com/15867575/164228679-42d36e2a-ac29-4279-8f2f-32b92b1167e2.jpg)

**Comment by strongoier** [comment]
# 22

Name: Calabash Brothers (Hu Lu Wa)
Link: https://github.com/strongoier/taichi-voxel-challenge
Screenshot:
![demo](https://user-images.githubusercontent.com/3251060/164261824-18371e78-5d2c-4c34-853d-2cef09b524b8.jpg)

**Comment by shumuxu** [comment]
Name:Shape
Link: https://github.com/shumuxu/voxel.git
Screenshot:
![screenshot2022-04-20-231405](https://user-images.githubusercontent.com/97172104/164267496-a70bc222-7a82-4d0d-98fb-2f79f51784d4.jpg)
![screenshot2022-04-20-231724](https://user-images.githubusercontent.com/97172104/164267526-a333b753-233b-46f4-bc10-c2fc32ef6bac.jpg)

**Comment by strongoier** [comment]
# 23

Name: Mahjong
Link: https://github.com/strongoier/taichi-voxel-challenge-mahjong
Screenshot:
![demo](https://user-images.githubusercontent.com/3251060/164501853-67012dbe-45c2-457f-960c-d9d563aaf0d0.jpg)
