### ISSUE TITLE
failed running the examples

### ISSUE THREAD

**Issue by Rexime** [taichi-dev/voxel-challenge#17]
PS C:\Users\14988\Documents\GitHub\taichi_work> & D:/anaconda/envs/taichi/python.exe c:/Users/14988/Documents/GitHub/taichi_work/example1.py
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, win, python 3.9.12
[Taichi] Starting on arch=vulkan
[I 05/04/22 13:23:37.158 41472] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:pick_physical_device@363] Found Vulkan Device 0 (AMD Radeon(TM) Graphics)
[I 05/04/22 13:23:37.158 41472] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:pick_physical_device@363] Found Vulkan Device 1 (NVIDIA GeForce RTX 3060 Laptop GPU)
[I 05/04/22 13:23:37.158 41472] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:create_logical_device@431] Vulkan Device "NVIDIA GeForce RTX 3060 Laptop GPU" supports Vulkan 0 version 1.3.194
Assertion failed: m_VulkanFunctions.vkGetDeviceBufferMemoryRequirements != nullptr, file D:/a/taichi/taichi/external/VulkanMemoryAllocator/include\vk_mem_alloc.h, line 14440

**Comment by yuanming-hu** [comment]
Could you try `pip install taichi==1.0.0`? There is a Vulkan bug on Windows with v1.0.1. The community already fixed it, and the fix will release on v1.0.2. Thanks! Let me know how things go.

**Comment by Rexime** [comment]
> 

thanks a lot! It worked.

**Comment by yuanming-hu** [comment]
You are welcome! Look forward to your artwork :-)
